"""Tests for the integration level: the spec, the generated top, the interface check.

These run without a solver. The 2x2 that needs one is bench/run_seam.py, which is
the experiment; this file is the regression cover that keeps the experiment's
inputs honest.
"""

import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from assertforge import compose  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPECS = os.path.join(ROOT, "bench", "specs")


def spec(name):
    s = compose.load_spec(os.path.join(SPECS, name))
    return s, compose.block_texts_for(s)


def test_width_of_reads_parameters_as_numbers():
    # Regression: parameter values arrive as source text, so `W-1` with W == '3'
    # raised TypeError and every parameterised port came back "unknown" -- the
    # width check did nothing on exactly the ports it exists for.
    assert compose.width_of("[W-1:0]", {"W": "3"}) == 3
    assert compose.width_of("[WIDTH-1:0]", {"WIDTH": "8"}) == 8
    assert compose.width_of("[2:0]", {}) == 3
    assert compose.width_of("", {}) == 1
    assert compose.width_of("[W-1:0]", {"W": "not_a_number"}) is None


def test_generated_top_instantiates_every_block():
    s, texts = spec("fifo_producer.json")
    top = compose.build_top(s, texts)
    for inst in s["instances"]:
        assert inst["module"] in top
        assert inst["inst"] in top
    assert top.startswith("// GENERATED by assertforge compose")
    assert "endmodule" in top


def test_generated_top_is_a_pure_function_of_the_spec():
    s, texts = spec("fifo_producer.json")
    assert compose.build_top(s, texts) == compose.build_top(s, texts)


def test_parameterised_ports_are_declared_at_the_right_width():
    s, texts = spec("fifo_producer.json")
    top = compose.build_top(s, texts)
    assert "wire [2:0] count;" in top      # FIFO count, [2:0] literal
    assert "wire [7:0] rd_data;" in top    # [WIDTH-1:0] with WIDTH=8


def test_mis_wiring_is_in_the_generated_file():
    # The two specs differ in exactly one connection, and the generated files
    # differ in exactly that. If they did not, the 2x2 would be measuring nothing.
    a, ta = spec("fifo_producer.json")
    b, tb = spec("fifo_producer_broken.json")
    top_a, top_b = compose.build_top(a, ta), compose.build_top(b, tb)
    assert ".wr_en(en)" in top_a
    assert ".wr_en(1'b1)" in top_b
    # The module name line differs too, and that is why the spec names differ. What
    # matters is that exactly one CONNECTION differs: if more did, the 2x2 would be
    # measuring a redesign rather than a wiring bug.
    def conns(text):
        return {l.strip() for l in text.splitlines()
                if l.strip().startswith(".") and not l.strip().startswith(".W")}
    assert sorted(conns(top_a) - conns(top_b)) == [".wr_en(en),"]
    assert sorted(conns(top_b) - conns(top_a)) == [".wr_en(1'b1),"]


def test_interface_check_reports_the_width_fault():
    s, texts = spec("fifo_producer_width_fault.json")
    issues = compose.check_ports(s, texts)
    kinds = [i[0] for i in issues]
    assert "width_mismatch" in kinds
    msg = compose.report_ports(issues)
    assert "zero-extension" in msg


def test_interface_check_does_not_accuse_a_shared_clock():
    # Regression: the first version tracked inputs as if they drove, so `clk` and
    # `rst` -- on every block -- came back as double drivers. A checker whose first
    # output is false accusations stops being read.
    s, texts = spec("fifo_producer.json")
    issues = compose.check_ports(s, texts)
    assert not [i for i in issues if i[1] in ("clk", "rst")], issues
    # And a spec that exposes its outputs and says something about them is clean.
    assert issues == [], issues


def test_interface_check_counts_seam_assertions_as_observers():
    # Regression: a net observed only by a seam assertion was reported dead, which
    # accused a spec that observes every net -- through its assertions, which is
    # where an assembly's outputs are meant to be observed.
    s, texts = spec("fifo_producer.json")
    s["assertions"] = [{"name": "only_mentions_full", "expr": "(full == (count == 4))"}]
    s["outputs"] = []           # take away the assembly outputs too
    dead = [i[1] for i in compose.check_ports(s, texts) if i[0] == "dead_output"]
    assert "full" not in dead
    assert "empty" in dead      # and the ones nothing observes are still named


def test_double_driver_is_caught():
    s, texts = spec("fifo_producer.json")
    for inst in s["instances"]:
        if inst["inst"] == "u_fifo":
            inst["connections"]["count"] = "prod_cnt"
    kinds = [i[0] for i in compose.check_ports(s, texts)]
    assert "double_driver" in kinds


def test_seam_assertions_pass_the_grammar_linter():
    for name in ("fifo_producer.json", "fifo_producer_broken.json",
                 "fifo_producer_width_fault.json"):
        s, _ = spec(name)
        assert compose.lint_assertions(s) == {}, name


def test_assertions_are_not_exempt_from_the_grammar():
    s, _ = spec("fifo_producer.json")
    s["assertions"] = [{"name": "sva_by_hand", "expr": "a |-> ##1 b"}]
    assert "sva_by_hand" in compose.lint_assertions(s)
