"""The wrapper generator -- the piece that must never touch the DUT."""

from assertforge.refine import build_harness, signals_of, mentions_dut_signal


DUT = """module sync_fifo #(parameter WIDTH = 8, parameter DEPTH = 4) (
    input  wire             clk,
    input  wire             rst,
    input  wire [WIDTH-1:0] wr_data,
    output reg  [1:0]       count
);
endmodule
"""


def test_wrapper_binds_parameters_named():
    w = build_harness(DUT, "sync_fifo", "always @(posedge clk) assert (count <= DEPTH);")
    assert ".WIDTH(WIDTH)" in w and ".DEPTH(DEPTH)" in w


def test_wrapper_mirrors_parameter_defaults_as_localparams():
    w = build_harness(DUT, "sync_fifo", "always @(posedge clk) assert (count <= DEPTH);")
    assert "localparam DEPTH = 4;" in w
    assert "localparam WIDTH = 8;" in w


def test_wrapper_instantiates_the_dut_and_keeps_the_body():
    body = "always @(posedge clk) assert (count <= DEPTH);"
    w = build_harness(DUT, "sync_fifo", body)
    assert "sync_fifo" in w and "u_dut" in w
    assert body in w


def test_wrapper_is_generated_code_not_edited_code():
    w = build_harness(DUT, "sync_fifo", "always @(posedge clk) assert (count <= DEPTH);")
    assert "GENERATED by assertforge" in w


def test_signal_harvest_includes_ports_and_ranges():
    sigs = signals_of(DUT)
    for s in ("clk", "rst", "wr_data", "count"):
        assert s in sigs


def test_vacuity_check_sees_a_constant_only_assertion():
    sigs = signals_of(DUT)
    assert not mentions_dut_signal("always @(posedge clk) assert (1 == 1);", sigs)
    assert mentions_dut_signal("always @(posedge clk) assert (count <= 4);", sigs)
